apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: dejmartins/order-service:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: bestbuy-secrets
            - configMapRef:
                name: bestbuy-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 3000
      targetPort: 3000
