apiVersion: v1
kind: Secret
metadata:
  name: bestbuy-secrets
type: Opaque
stringData:
  ORDER_QUEUE_URI: "amqps://pet-store.servicebus.windows.net"
  ORDER_QUEUE_HOSTNAME: "pet-store.servicebus.windows.net"
  ORDER_QUEUE_USERNAME: "RootManageSharedAccessKey"
  ORDER_QUEUE_PASSWORD: "W0+3Slh1ZriCyWbUjt8vmp75arT1BK8Pk+ASbCmW2dk="
  ORDER_DB_URI: "mongodb://mongodb:27017"
